### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by AbbasTechievolve** [shopifychamp/shopify-api-php-sdk#4]
**Describe the bug**
when i was trying to delete the ScriptTag By using SDK then a error occurred while all of the Api's request is working Fine like POST/GET but i am not understanding why it is happening when i choose the DELETE operation ,

This is my error : 
Fatal error: Uncaught Shopify\Exception\ApiException: Client error: `DELETE https://edd46b2c4ddb1469dbef46434614bfbab:***@testtechievolve.myshopify.com/admin/api/2019-10/script_tags.json?id=187190444172` resulted in a `406 Not Acceptable` response in C:\xampp\htdocs\shopifySDK\vendor\shopifychamp\shopify-api-php-sdk\src\Client.php:277 Stack trace: #0 C:\xampp\htdocs\shopifySDK\vendor\shopifychamp\shopify-api-php-sdk\src\Client.php(200): Shopify\Client->request('DELETE', 'https://edd46b2...', Array) #1 C:\xampp\htdocs\shopifySDK\header.php(19): Shopify\Client->call('DELETE', 'script_tags', Array) #2 C:\xampp\htdocs\shopifySDK\index.php(2): require('C:\\xampp\\htdocs...') #3 {main} thrown in C:\xampp\htdocs\shopifySDK\vendor\shopifychamp\shopify-api-php-sdk\src\Client.php on line 277

This is my code :
187190444172 : This is my created ScriptTag id

 $script_tag_array = array(
	'id' => 187190444172
);
$scriptTag = $client->call('DELETE','script_tags',$script_tag_array);
echo "<pre>";
print_r($scriptTag); 

**Expected behavior**
I want to delete any ScriptTag by using this SDK  .

**Error Screenshots**
image URL : https://www.awesomescreenshot.com/image/34970264?key=05e25bf63ba437cdf61458e5832dcc14

**Additional context**
when i was trying to delete the ScriptTag By using SDK then a error occurred while all of the Api's request is working Fine like POST/GET but i am not understanding why it is happening when i choose the DELETE operation , can you please check my above code and if i am doing wrong in my code then please correct them. 

Your Any Help must be appreciated ,

Thanks

**Comment by AbbasTechievolve** [comment]
issue resolved now
